### ISSUE TITLE
Exceptions cause the update loop to crash out

### ISSUE THREAD

**Issue by BenWoodford** [filcole/home-assistant#9]
Updates die out if there is an exception while refreshing data.

https://github.com/filcole/home-assistant/blob/nissanleaf/homeassistant/components/nissan_leaf.py#L176

Presumably just needs a try/catch, but it's probably also a good idea to still output the stack trace so that the actual exceptions can be squashed too.

**Comment by filcole** [comment]
I've added a few try/catches, but a few areas need bedding in

**Comment by filcole** [comment]
No recent errors after try/catch additions. Closing.
